package com.lzx.guanchajava.POJO


const val ACTION_CHANGE_SHOW_MODE = "com.laz.guanchajava.ACTION_CHANGE_SHOW_MODE"
const val ACTION_LOGIN_IN = "com.lzx.guanchajava.LOGIN_IN_BY_BROADCAST"
const val ACTION_LOG_OUT = "com.lzx.guanchajava.LOGIN_OUT_BY_BROADCAST"
object TAG {
    val POST_TOPIC_ID = "POST_TOPIC_ID"
    val POST_TOPIC_NAME = "POST_TOPIC_NAME"
    val POST_TOPIC_ARTICLE = "POST_TOPIC_ARTICLE"
    val POST_TOPIC_SUBSCRIBE = "POST_TOPIC_SUBSCRIBE"
    val POST_TOPIC_HAS_ATTENTION = "POST_TOPIC_HAS_ATTENTION"
    val POST_TOPIC_PIC = "POST_TOPIC_PIC"

    val ACTIVITY_IMAGE = "ACTIVITY_IMAGE"

    val ACTIVITY_TAGS = "TAGS_ID"

    val CODE_LOGIN_REQUEST = 0x11
    val CODE_LOGIN_RESULT = 0x12

    val TAG_FRAGMENT_NEWS_LIST_URL = "TAG_FRAGMENT_NEWS_LIST_URL"
    val TAG_FRAGMENT_NEWS_LIST_LOADNOW = "TAG_FRAGMENT_NEWS_LIST_LOADNOW"


    val USER_INFO_REPLY = "USER_INFO_REPLY"
    val USER_INFO_ARTICLE = "USER_INFO_ARTICLE"
    val USER_INFO_PRAISE = "USER_INFO_PRAISE"
    val USER_INFO_REPLIED = "USER_INFO_REPLIED"
    val USER_INFO_PRAISED = "USER_INFO_PRAISED"
    val USER_INFO_VOTED = "USER_INFO_VOTED"
    val USER_INFO_ATTENTION = "USER_INFO_ATTENTION"


    val PREF_NIGHT_MODE = "pref_night_mode"
}