package com.lzx.guanchajava.POJO.bean.topic

data class Data(
        val access_device: Int,
        val code_type: Int,
        val collection_count: Int,
        val comment_count: Int,
        val content: String,
        val content_org: String,
        val created_at: String,
        val has_attention: Boolean,
        val has_collection: Boolean,
        val has_praise: Boolean,
        val has_vote: Boolean,
        val id: Int,
        val is_anonymous: Boolean,
        val orderby_value: Int,
        val pass_at: String,
        val pic: String,
        val post_url: String,
        val post_url_night: String,
        val praise_num: Int,
        val share_url: String,
        val status: Int,
        val summary: String,
        val title: String,
        val topics: List<TopicX>,
        val user_description: String,
        val user_id: Int,
        val user_level: String,
        val user_level_logo: String,
        val user_nick: String,
        val user_photo: String,
        val view_count: Int,
        val vote_info: List<VoteInfo>
)